sbatch main.py --data-name hapt --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name hapt --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name hapt --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name hapt --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name hapt --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name hapt --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name hapt --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name hapt --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name dg --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name dg --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name dg --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name dg --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name dg --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name dg --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name dg --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name dg --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name wisdm --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name wisdm --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name wisdm --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name wisdm --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name wisdm --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name wisdm --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name wisdm --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name wisdm --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name dsads --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name dsads --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name dsads --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name dsads --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name dsads --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name dsads --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name dsads --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name dsads --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name oppo --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name oppo --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name oppo --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name oppo --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name oppo --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name oppo --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name oppo --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name oppo --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name pamap2 --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name pamap2 --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name pamap2 --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name pamap2 --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name pamap2 --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name pamap2 --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name pamap2 --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name pamap2 --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name rw --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name rw --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name rw --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name rw --shuffle --model-type attend --seed 1 --difference --filtering --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
sbatch main.py --data-name rw --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5
sbatch main.py --data-name rw --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 0.5 --random-augmentation-prob 1
sbatch main.py --data-name rw --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 0.5
sbatch main.py --data-name rw --shuffle --model-type attend --seed 1  --mixup-argmax --root-path ../../../datasets --filter-scaling-factor 1.0 --mixup-probability 1 --random-augmentation-prob 1
